### ISSUE TITLE
MineTweaker support not working? 

### ISSUE THREAD

**Issue by EPIICTHUNDERCAT** [primetoxinz/Meltery#2]
Says "member is missing" if you use what you said to use. i tried mods.meltery.Meltery, meltery.Meltery, but it doesnt seem to work.

**Comment by primetoxinz** [comment]
Do you have [MTLib](https://minecraft.curseforge.com/projects/mtlib) installed?

**Comment by EPIICTHUNDERCAT** [comment]
you're so right! I totally forgot that minetweaker has its stuff built in!
